### ISSUE TITLE
Support additional Data types

### ISSUE THREAD

**Issue by Drachir000** [Drachir000/SimpleConfigLib#10]
Currently this is the List of supported data types:
- String
- int
- long
- float
- double
- boolean
- Configuration
- JSONArray
- any kind of Enum

These are to add:
- byte
- short
- char

Also test the implementation, whether they can be retrieved again, etc.

**Possible Problem:**
Setting a char with the Obj `set()` Method stored it as an String and casting a String to a char is not possible.
**Solution:**
```java
Sting s; // The expected to be char as a String
if (s.length() == 1) {
    return s.charAt(0);
}
// TODO JSONException -> is no char
```

**Comment by Rednaxela000** [comment]
Closed with #11.
